server {
  listen 80;
  server_name _;

  root /var/www/html/public;
  index index.php index.html;

  # Laravel routing
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
  }

  location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|webp)$ {
    expires 7d;
    access_log off;
  }
}
